- name: Install Nginx
  hosts: Web
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Start Service
      ansible.builtin.systemd_service:
        state: started
        name: nginx
        enabled: true