- name: Install Nginx
  hosts: Web
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Start Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true



- name: Install Nginx
  hosts: Web
  become: true
  roles:
    - sample

