- name : Demo for AWS Parameter store
  hosts : localhost
  connection: local
  tasks:
    - name: recommend to use with aws_ssm lookup plugin
      ansible.builtin.debug:
      msg: "{{ lookup('amazon.aws.aws_ssm', 'rds.dev.database_name', region='us-east-1') }}"